### ISSUE TITLE
New Pseudo Comments

### ISSUE THREAD

**Issue by hardyp** [SAP/code-pal-for-abap#13]
The obvious problem with the new Pseudo Comments is that they are not recognized by the traditional extended program check as in:-

![image](https://user-images.githubusercontent.com/7078215/81366701-a5898e00-912e-11ea-9f91-44ba3e827c22.png)

Therefore there is no way to get the extended program check and the code inspector to give a clean slate.

**Comment by hardyp** [comment]
Looking in the database I think Pseudo Comments can only be 10 characters long as per data element PCOMSLIN. So CHECK_POSITION is 14 characters long hence the truncation. Obviously it is not in the check table anyway.

**Comment by eugen-guenther-sap** [comment]
Thank you for reporting the issue we will investigate it.

**Comment by hardyp** [comment]
I work around this by dropping the EC# at the start of the new Pseudo comments. That way they do not show up on the extended program check nor the Clean ABAP Checks.

**Comment by eugen-guenther-sap** [comment]
@All,

we could shorten the pseudo comments in all checks to 10 characters due to SLIN compatibility.
If so, the pseudo comments would get a new name and the users have to adjust the pseudo comments they already used.

What do you think about this solution?

**Comment by eugen-guenther-sap** [comment]
I tested the SLIN check, it reacts to the `"# EC` part of the check, not to the length.
And we cannot change the `"# EC` part because SCI cannot exclude the issue without it.

But i would say if it is just a note and nothing got blocked i would just ignore SLIN without changing anything.
If you find another solution i'm open for new ideas.
