### ISSUE TITLE
False Positive in "Declaration in IF Check"

### ISSUE THREAD

**Issue by smb** [SAP/code-pal-for-abap#20]
IMO we have a false positive in 

https://github.com/SAP/code-pal-for-abap/blob/master/docs/checks/declaration-in-if.md

When you have the following code:

```
....
  IF condition.
    DATA(my_log_value) = |{ val1 } + { val2 }|. 
    MESSAGE i001(/absw/messageclass) WITH my_log_value INTO DATA(msgtext).
  ENDIF.
ENDMETHOD.

```

The check reports the my_log_value line, because it's delcared within the IF - but since it's not used outside afterwards, this shouldn't be an error.

In other languages this would be covered by variable scope (my_log_value) only available within the IF block - but even without scoping it's much cleaner if you dont declare this outside.

**Comment by maxim-engel-sap** [comment]
Hi @smb . That’s a good point and we had already a discussion regarding this issue in the team.

I tried and was not able to come up with a solid check to provide the requested feature. The possibilities to use attributes in ABAP are just too many to find them reliably. I see your point of having the declaration right in front before using it. Especially in your example, that makes absolutely sense.

But I think also about another point, having readable and understandable code for non-ABAP-natives. I would go even further and say, that not every ABAP developer know about the fact, that declarations in optional branches are handled at the beginning of the method by the compiler. Since there is no scoping, we could just declare the attributes right in front of the IF, then the scope is clear and could not be misunderstood.

In the end, you simply decide, which approach you want to follow. The check could be configured as warning or notification to lower the need of correction. The check could also be deactivated for the whole system if you and/or your team finds it more confusion than beneficial.

Sorry, that we can’t provide a solution here. But well, it's open source, and I'm sure there are very smart people out there, maybe someone will take the challange.
