### ISSUE TITLE
Prefer CHANGING to EXPORTING with the 'pass value' flag not set

### ISSUE THREAD

**Issue by lucasborin** [SAP/code-pal-for-abap#289]
An EXPORTING parameter with the 'pass value' flag NOT set will behave like a CHANGING parameter.

```abap
EXPORTING
  VALUE(ev_x) TYPE i.
```

**Comment by suynwa** [comment]
Please see the official documentation on [Pass by Reference or Pass by Value](https://help.sap.com/doc/abapdocu_755_index_htm/7.55/en-US/index.htm?file=abenformal_parameters_oview.htm)
Always using pass-by-value for exporting parameters might not be performant (e.g., big internal tables)

I would rather check that the exporting parameter (passed-by-reference) should be "initialized" at the start of the routine. 

``` abap
methods FOO
  exporting
    E_BAR type TT_HUGE_RECORDS.

method FOO.
  clear BAR. " Check should return OK
endmethod.
```

**Comment by RolfMantel** [comment]
On the assumption that we use "returning" rather than "exporting" most of the time as per Clean Code recommendations, the "EXPORTING" would likely be restricted to performance critical code lines.
With Clean Code, we are also likely to have a deep  call stack.  In order to benefit for using "EXPORTING" at all, I need to pass out the EXPORTING" parameter a large number of times.  In this situation, I do not want to CLEAR it 10 times before using it the first time.  In this case, ABAP can optimize "lazy copy" during "call by value" but cannot optimize the repeated "CLEAR".

**Comment by suynwa** [comment]
@RolfMantel Could you specify maybe with an example where you would need to pass the same internal table multiple times as exporting param?

So, are you suggesting that it's OK to pass huge internal tables by value?

**Comment by RolfMantel** [comment]
> So, are you suggesting that it's OK to pass huge internal tables by value?

The ABAP optimizer executes "lazy copy": the statement 
a[] = b[].
does not copy the table but only copies the reference.  The physical copying only happens when I modify the table a[] while table b[] still exists.  So specifically, at the end of a method, the internal copy of the table is nuked, and there is no need to do a physical copy.

**Comment by suynwa** [comment]
Thanks for refreshing my memory. I remember blog https://blogs.sap.com/2017/07/30/the-mysteries-of-the-returning-parameter/ where Lars had presented a detailed analysis along with the runtimes & memory consumption.

**Comment by lucasborin** [comment]
Related to https://github.com/SAP/styleguides/issues/150.

**Comment by D072189** [comment]
There is already a check in the Extended Program Check (SLIN) that raises findings when by-reference EXPORTING parameters are not initialized at start of a function, so there is already an equivalent check.
