### ISSUE TITLE
RETURNING Name: allow prefixes

### ISSUE THREAD

**Issue by jmg-sap** [SAP/code-pal-for-abap#335]
Hi, 

the check documentation for the [RETURNING Name](https://github.com/SAP/code-pal-for-abap/blob/master/docs/checks/returning-name.md) check references the ABAP Styleguide section [Consider calling the RETURNING parameter RESULT](https://github.com/SAP/styleguides/blob/master/clean-abap/CleanABAP.md#consider-calling-the-returning-parameter-result) which reads: "call the parameter RESULT, or something like **RV_RESULT** if you prefer Hungarian notation". 

It seems to me, however, that only "RESULT" is currently accepted by the check, see the code in Y_CHECK_RETURNING_NAME->HAS_RETURNING_WITH_WRONG_NAME. Could this check be modified to allow for prefixes? This would e.g. help the reader to understand whether they are dealing with a standard / sorted / hashed result table (e.g. RT_RESULT / RTS_RESULT / RTH_RESULT).

Kind regards,
Jörg-Michael

**Comment by Hany17** [comment]
I can't agree more. In ABAP it is quite vital, since in abap those types are quite useful.

**Comment by larshp** [comment]
just disable the check? if your team's development guidelines require prefixes, there is

https://blogs.sap.com/2018/05/11/all-your-abap-prefixes-are-belong-to-us/
and
https://rules.abaplint.org/method_parameter_names/

**Comment by suynwa** [comment]
Tbh, i personally don't use Hungarian notations. But i am definitely against using RT_RESULT / RTS_RESULT / RTH_RESULT to distinguish between standard, sorted and hashed tables. 
- What advantage does it bring to distinguish between the table types?
- What happens if you change the type from hashed to sorted, would you rename your parameter?

The ADT context help (F2) should be sufficient.

**Comment by lucasborin** [comment]
I'm with Lars. Clean Code (by Uncle Bob) and Clean ABAP encourages you to get rid of all the encoding prefixes.
What exatcly would you allow as a prefix?

**Comment by jmg-sap** [comment]
Hi everyone, 

thanks for your comments! Prefixes – I know, I know. I am not using them in my private programming projects, either. However, the styleguide also says code style should be consistent, right? So does the [blog](https://blogs.sap.com/2018/05/11/all-your-abap-prefixes-are-belong-to-us/) that Lars shared. So, if in our solution, several years worth of code have been using prefixes, we don't suddenly start abandoning them in new methods or for certain parameter types, and if our team's programming guidelines say we are using prefixes, it makes sense to consistently follow that, doesn't it? 

Deactivating the check isn't an option either, because the check scope (and its severity: Error = blocking transport) is decided far beyond team level in our case. We would therefore have to put "#EC RET_NAME everywhere. 

So, all I'm saying is that if the Clean ABAP Styleguide reads "call the parameter RESULT, or something like RV_RESULT if you prefer Hungarian notation", then the check should allow for that, too – or the Styleguide should be changed to "call the parameter RESULT, no prefixes allowed, even if you use them elsewhere". 

@lucasborin: With respect to the check implementation, I would simply allow any prefix (rather than just a list of specific prefixes), i.e. modify the check to just make sure the returning parameter contains (or, if you insist, ends with) the word "result". 

Kind regards,
Jörg-Michael

**Comment by lucasborin** [comment]
> However, the styleguide also says code style should be consistent, right? So does the [blog](https://blogs.sap.com/2018/05/11/all-your-abap-prefixes-are-belong-to-us/) that Lars shared. So, if in our solution, several years worth of code have been using prefixes, we don't suddenly start abandoning them in new methods or for certain parameter types, and if our team's programming guidelines say we are using prefixes, it makes sense to consistently follow that, doesn't it?

Yes, it does. However, it is subjective. So, what is the acceptable 'level' to change the dev style? (form/method, program/class, package, feature module (sd/mm), etc).

That is why code pal has the object creation date filter. You can set, for instance, that all the objects created after Jan/2021 are not relevant for the new style guide. 

IMO, you should keep the same 'unit' dev style (form/method level). Once you create something new, which means a new feature probably, you should follow the new style guide to enjoy its advantages in the future. Otherwise, you will keep creating old-fashioned code which goes against the clean code benefits (easy to understand, easy to test, isolation, etc).

> Deactivating the check isn't an option either, because the check scope (and its severity: Error = blocking transport) is decided far beyond team level in our case. We would therefore have to put "#EC RET_NAME everywhere.

Would the object creation date filter help here?

> So, all I'm saying is that if the Clean ABAP Styleguide reads "call the parameter RESULT, or something like RV_RESULT if you prefer Hungarian notation", then the check should allow for that, too – or the Styleguide should be changed to "call the parameter RESULT, no prefixes allowed, even if you use them elsewhere".

I see your point. But keep in mind that the Clean ABAP does not oblige you to do something, but so recommend you to do so, and the Hungarian notation goes against the clean code.

Robert C. Martin said:
> ... nowadays HN and other forms of type encoding are simply impediments. They make it harder to change the name or type of a variable, function, member or class. They make it harder to read the code. And they create the possibility that the encoding system will mislead the reader.

...

> @lucasborin: With respect to the check implementation, I would simply allow any prefix (rather than just a list of specific prefixes), i.e. modify the check to just make sure the returning parameter contains (or, if you insist, ends with) the word "result".

It is not that easy. People can use `EV_RESULT` for returning then. That is why I mentioned we should go deeper and ask the style guide team to support/define Hungarian notation as well. Again, it goes against the clean code rules (not Clean ABAP only).

**Comment by estevao-schultz-neto-SAP** [comment]
If the check is hard to digest (but actually not wrong), why not reducing its severity or even deactivating it from your check scope? This channel here is the right channel for discussing everything related to the check itself (scope, purpose, feasibility,...) but not how a valid check should be applied for your team/project/organisation.

**Comment by estevao-schultz-neto-SAP** [comment]
We will clarify this with the CLEAN ABAP gurus and adjust the CHECK accordingly. If it is being used in any SAP Internal Team on a compulsory basis, we will adjust it as well. thank you.

**Comment by RolfMantel** [comment]
> But keep in mind that the Clean ABAP does not oblige you to do something, but so recommend you to do so, and the Hungarian > notation goes against the clean code.

This is true as long as Clean ABAP is applied voluntarily but not when Clean ABAP is enforced on program level.
We have an internal inconsistency anyways between the two requirements
1) the method should return "result"
2) tables should be plural, i.e. when a method returns a table, it should return "results" rather than "result"

**Comment by jordao76** [comment]
The guideline to use the name `result` is simply an acknowledgement that it's a very special type of parameter, and it makes it obvious what it refers to: the sole returning parameter. Its singular form is sufficient to capture that intent, it doesn't matter if it's a table type or a class representing a message container or anything that is "plural" in nature. Many other languages simply return the result without naming it, so "result" is simply a way to make the returning parameter both _obvious_ and _invisible_. In most cases, the method name itself should make it obvious what it returns, no need for the returning parameter name to parrot it.

Either way, the guidelines say "consider" calling the returning parameter `result`, of course it can be something else if it makes more sense, like when it's not obvious what the method returns given its name.

**Comment by RolfMantel** [comment]
> Either way, the guidelines say "consider" calling the returning parameter `result`, of course it can be something else if it makes 
> more sense, like when it's not obvious what the method returns given its name.

We have to be careful to separate between "Clean ABAP as recommendation" and "enforcing a SAP-wide common style"; wherever the guideline says "consider", the technical tool must not throw an error, default should be notification (and then we do not need to discuss about minor details like this).

In my limited (nine-month) experience of clean code, the benefit of naming the return parameter is twofold:

1. inside the method, `append line to result**s**` and `result = line` are correct at first glance while `append line to result `needs further investigation
2. code completion (which inserts `receiving results =`  which I then delete) helps me catch confusions between methods acting on a single line and methods acting on a table, which is sometimes confusing when a table with more than one line is a special case that only happens rarely
3. The idea to use one structured return parameter containing a table and a status instead of exporting two parameters  (e.g. the method "find_customers" returns not a table of customers but a structure containing a table) makes the distinction between  _result structure_ and _result payload_ (which is a table) even more confusing for the author (by now I agree that this style can simplify readability)

**Comment by lucasborin** [comment]
> We have to be careful to separate between "Clean ABAP as recommendation" and "enforcing a SAP-wide common style"; wherever the guideline says "consider", the technical tool must not throw an error, default should be notification (and then we do not need to discuss about minor details like this).

We just have to split the scopes here, as here we can argue about the tool only. If we have feedback for SAP internal processes, we must discuss it internally with the responsible team. I mean, we can decide that the default threshold of a Check is a warning, but it won't affect any SAP internal tool. 

> In my limited (nine-month) experience of clean code, the benefit of naming the return parameter is twofold:
> 1. inside the method, append line to result**s** and result = line are correct at first glance while append line to result needs further investigation
> 2. code completion (which inserts receiving results = which I then delete) helps me catch confusions between methods acting on a single line and methods acting on a table, which is sometimes confusing when a table with more than one line is a special case that only happens rarely
> 3. The idea to use one structured return parameter containing a table and a status instead of exporting two parameters (e.g. the method "find_customers" returns not a table of customers but a structure containing a table) makes the distinction between result structure and result payload (which is a table) even more confusing for the author (by now I agree that this style can simplify readability)

The same applies here. We are talking about how the Clean Code at ABAP. Therefore, I recommend you to share your perspective in the Clean ABAP thread directly (https://github.com/SAP/styleguides/issues/190).

Now, regarding code pal, we will keep the Check as it is. IMO, it follows the common agreement based on the style guide. 
By the way, it looks like they share the same opinion as Jordão and we (code pal admins).

So, if you do not mind, I will close this issue as it is not related to the tool itself, but so a clean code decision. 
Let's continue there => https://github.com/SAP/styleguides/issues/190
