### ISSUE TITLE
Prefer IS NOT to NOT IS

### ISSUE THREAD

**Issue by jochen-beurer** [SAP/code-pal-for-abap#338]
This check should accept predicative method calls like this:

```abap 
if not meth( ... ).
  " ...
endif.
```

**Comment by lucasborin** [comment]
Following the Clean ABAP:
- [Try to make conditions positive](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md#try-to-make-conditions-positive)
- [Prefer IS NOT to NOT IS](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md#prefer-is-not-to-not-is)

So, for instance, we should use `IF is_invalid()` instead of `IF NOT is_valid( )`.
How about it?

**Comment by jochen-beurer** [comment]
We have to separate two things here.

The check fails to distinguish between predicate expressions and predicate functions/methods. The "prefer IS NOT to NOT IS" rule applies to predicate expressions, and of course I prefer ```abap if ... is not bound.``` to ```abap if not ... is bound.``` But for predicate functions like ```abap line_exists( ... )``` or ```abap matches( ... )``` there is no built-in negation, and therefore, in my opinion, they must not be checked for compliance with the "prefer IS NOT to NOT IS" rule. 

The same applies principally to predicate methods. But you are right, the "try to make conditions positive" rule suggests to rather check ```abap is_invalid( )``` than ```abap not is valid( )```. But if valid actually means that there does NOT exist some special line in some internal table, sticking to the rule ends up in some weird comparison with abap_false which IMO is not better than simply checking ```abap if not line_exists( ... ).```

**Comment by lucasborin** [comment]
Yes, I agree with you. Standard functions (like `line_exists( )` and `matches( )`) should not be checked. Actually, the `line_exists( )` is not being reported since Code Pal release 1.08 as we fixed it. Do you see any other function to be exempted as well? If so, please, let me know then I enhance the check here.

Now, regarding the non-standard functions (like your own method/function), I would say it is better to recommend the users to keep the condition positive as recommended by the Clean ABAP.

**Comment by jochen-beurer** [comment]
Standard predicate functions (in ABAP 7.5) are contains, contains_any_of, contains_any_not_of, line_exists, matches.

**Comment by lucasborin** [comment]
Reference:
- https://help.sap.com/doc/abapdocu_750_index_htm/7.50/en-US/abencontains_functions.htm

`contains_any_not_of` implments the negative form of `contains_any_of`.

**Comment by jochen-beurer** [comment]
> Reference:
> 
> - https://help.sap.com/doc/abapdocu_750_index_htm/7.50/en-US/abencontains_functions.htm
> 
> 
> 
> `contains_any_not_of` implments the negative form of `contains_any_of`. 

Of course, it does not, cf. the table in the linked ABAP docu: `contains_any_of( val = val sub = '0123456789' )` means that val contains at least one digit, aka `val ca '0123456789'`, while `contains_any_not_of( val = val sub = '0123456789' )` means that val doesn't contain only digits, aka `val cn '0123456789'`, and this is obviously not a pair of opposites.

**Comment by lucasborin** [comment]
Ops, thanks for sharing it. I'll adjust the pull request accordingly.

**Comment by lucasborin** [comment]
Feel free to test it in the next release (beta) 1.14.0
