### ISSUE TITLE
Downportability

### ISSUE THREAD

**Issue by lucasborin** [SAP/code-pal-for-abap#340]
A new Check that validates if the respective code is downportable to a specific SAP_BASIS / SAP Release. 

Suggestion: Y_CHECK_DOWNPORTABILITY

**Comment by D072189** [comment]
This doesn't seem to be related to Clean ABAP at all, and it is also a very thorny topic - "remote syntax checks" are very tricky and non-trivial to implement, since ABAP programs can refer to arbitrary other ABAP and Data Dictionary information in the system. (I also know of some attempts to integrate such functionality directly in ADT)

I understand it would be great for certain use cases to have this, but I don't think this is the right place for it.
