### ISSUE TITLE
Warning for 0 Public Attributes and 0 Public Methods Without an Interface

### ISSUE THREAD

**Issue by Ldmade** [SAP/code-pal-for-abap#427]
**Check Name**
y_check_num_public_attributes
y_check_is_interface_in_class

**Actual Behavior**
Raises a warning/error for 0 public attributes and 0 public methods without an interface
![codePalCapture](https://user-images.githubusercontent.com/27431038/123963409-b809fb00-d9b2-11eb-94fd-c2bd6d988651.PNG)

**Expected Behavior**
When I have 0 public attributes and all methods behind an interface, I should not get a warning/error message.

**Comment by lucasborin** [comment]
```abap
INTERFACE a.
  METHODS run.
ENDINTERFACE.

CLASS b DEFINITION.
  PUBLIC SECTION.
    INTERFACES a.
ENDCLASS.

CLASS b IMPLEMENTATION.
  METHOD a~run.
  ENDMETHOD.
ENDCLASS.
```

![image](https://user-images.githubusercontent.com/5233413/123978217-11176600-d996-11eb-96f8-b53eb9c58233.png)

**Comment by lucasborin** [comment]
Could you please share a code snippet that raises the first warning?
`0 public methods without interface!`

The example above raised the second warning only.

**Comment by Ldmade** [comment]
![image](https://user-images.githubusercontent.com/27431038/123985773-08d71f00-d9c6-11eb-832b-4b2c155cc73a.png)
I guess the constructor is the reason.

**Comment by lucasborin** [comment]
Regarding the y_check_is_interface_in_class,

Are you using the [Profiles ](https://github.com/SAP/code-pal-for-abap/blob/master/pages/how-to-configure.md) feature? If so, could you please remove the Check from the respective Profile and assign it again?

![image](https://user-images.githubusercontent.com/5233413/123995801-103a0080-d9a5-11eb-888b-e8a986bce228.png)

In the past, this Check threshold was by default zero. Now, it is one. If you have been using the code pal since the former version,  the above-mentioned reassignment is required. 

If you are not using the Profile feature, could you please deactivate the Check from the Code Inspector Variant and activate it again? (transaction SCI).

**Comment by lucasborin** [comment]
Similar to [Number of public attributes threshold (#158)](https://github.com/SAP/code-pal-for-abap/issues/158)

**Comment by Ldmade** [comment]
"Did you try to turn it off and on again?" :-)
Worked for me. Thank you
