### ISSUE TITLE
Checks on SAPForms

### ISSUE THREAD

**Issue by StefanRiedel-Seifert** [SAP/code-pal-for-abap#558]
> 💡 Code pal for ABAP follows the [Clean ABAP](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md). If the issue relates to coding style, please submit it [here](https://github.com/SAP/styleguides/issues). 

**Check Name**
> FORM Routine Usage

**Actual Behavior**
> CodePal checks also generated forms in code artefacts of SAPForms
![image](https://user-images.githubusercontent.com/75482283/158962827-68d6951c-1a00-4442-882d-6a179db61774.png)
![image](https://user-images.githubusercontent.com/75482283/158962948-3c879335-d958-438f-8876-15b222dc70b7.png)
![image](https://user-images.githubusercontent.com/75482283/158963059-cf8bfbab-9428-4ad8-8e29-60ace2553a4c.png)

**Expected Behavior**
> We cannot avoid usage of these artefacts. They are generated in the namespace  /1BCDWB/. Such namespaces should be excluded.
I assume, that the form %GLOBAL_INIT was found, because there is custom code inside

**Comment by D072189** [comment]
In which ABAP release does this happen? Starting from SAP_BASIS 7.51, there should be generic logic in the ATC that suppresses findings in generated code.

Unfortunately, 7.40 and 7.50 do not contain the necessary APIs to suppress findings in generated code there.

**Comment by StefanRiedel-Seifert** [comment]
It's on the newest S/4-Release: 7.55. Is there a place, there we can remove the finding? any kind of BAdI?

**Comment by D072189** [comment]
Right, I can reproduce this.

So this happens because the form declaration itself is classified as "not generated" here (which I _think_ is technically correct - some developer manually created this form, even if they had no choice but to create it as a form). Unfortunately, there is no way to see on the level of the classification that there was no choice but to use a form.

The best solution would be to change the FORM usage check ([Y_CHECK_FORM](https://github.com/SAP/code-pal-for-abap/blob/master/src/checks/y_check_form.clas.abap)) to not check these kinds of objects that necessarily contain forms (object type SFPF, SSFO), as it doesn't make any sense in those contexts.

**Comment by StefanRiedel-Seifert** [comment]
Any code snippet?

**Comment by D072189** [comment]
Ah, by "solution" I meant changing the code of the check - e.g. by redefining the RUN method and only doing something (i.e. calling the super->run) if the object type isn't a form object

**Comment by StefanRiedel-Seifert** [comment]
Okay, a very simple approach:

    IF me->object_type <> 'SFPF'.
      CALL METHOD super->run.
    ENDIF.

I think i will build a generic exclusion framework :-)

**Comment by steve192** [comment]
@D072189 can't we include such a framework in code-pal iteself?
I'm thinking of an additional setting in this popup where you can limit the check to specific object types (or exclude object types):

> That are the only options: ![image](https://user-images.githubusercontent.com/75482283/158979254-50109fc1-5ee4-4e78-9e0b-75b2873fb4e0.png) 

I would rather not like to force every user implement this by themselves. (This would also break simple upgradability of the code-pal framework, we want to benefit from future nice features 😃  )

**Comment by D072189** [comment]
I don't think the checks should be configurable to be restricted to object types - if you just don't want to check some object types at all, don't make them part of the object set that you're checking.

I _do_ think that this specific check that emits findings for every FORM declaration shouldn't be checking SFPF and SSFO objects because these always contain forms and it doesn't make sense to tell the user not to use forms - they have to use forms in the the context of these objects. In principle checks declare which types they check in their TYPELIST attribute - the form check inherits an entry for "all program-like objects" here from its superclass CL_CI_TEST_SCAN. 

So the clean solution would probably to add exclusion entries for SFPF and SSFO to the TYPELIST in the constructor of this particular check. This change - excluding form objects from this check - should be part of code-pal, if someone wants to make a pull request, I'd be happy to review it.

**Comment by StefanRiedel-Seifert** [comment]
Why no further attributes on the level of the check routine?
![image](https://user-images.githubusercontent.com/75482283/159003016-0f33b202-b371-4981-a8d6-3101afd00f41.png)

**Comment by StefanRiedel-Seifert** [comment]
This is a methodology to store things in the context of the check. This is common practize?
![image](https://user-images.githubusercontent.com/75482283/159003390-f0bd4f13-dd27-4392-8208-41a0bb4d184d.png)

**Comment by steve192** [comment]
I will try to implement @D072189's solution and open a pull request

**Comment by steve192** [comment]
hm.. not that easy as thought. CL_CI_INSPECTION->preprocess_objects ignores all exclusions from the typelist whenever a "1PRG" (aka all program like types) is present.
So we can't simply add exclusions for SFPF and SSFO.


Options I can think of:
1. Replace 1PRG with the real program like types (this is possibly very time intensive, there are probably a lot of legacy types)
2. Replace 1PRG with the most relevant program like types like PROG, CLAS etc. (this most likely ignores some types where the form check would also be beneficial)
3. Abort the check in the check's run method when the type matches a blocklist (this would somehow violate ATC architecture with its typelist)

Any more options you can think of?

**Comment by D072189** [comment]
The actual bug relevant for execution is in CL_CI_TESTS->RUN (but it's of the same form as the one in CL_CI_INSPECTION), I'll see what I can do about that - probably no one ever triggered this because saying you want to check all program-like objects and then saying you don't want to check a particular type of these is a rather uncommon use case. But it is definitely a bug because it contradicts the normal semantics of range tables in ABAP.

The pragmatic solution would be both adding the exclusions to the typelist _and_ aborting in the run method. The "principled" solution would be adding the exclusion to the typelist and waiting for a SAP note to fix this bug and then tell everyone to install that note if they want this check to work correctly.

**Comment by steve192** [comment]
The usecase we have is that the ATC checks are triggered via ci on all packages contained in a git repository. 
We don't want to filter for object types in our ci pipelines.

I will implement the pragmatic solution and you will sometime take care of a sap note?

**Comment by StefanRiedel-Seifert** [comment]
In my opinion we may run into this problem all the tim, when SAP generates form routine includes like this way. Another example may be Copy Control.
And therefore we cannot decide on TADIR object type, because they did not have this. The are regular form routines?

**Comment by StefanRiedel-Seifert** [comment]
i checked this: in the area of copy control (transaction VOVM), SAP generates inludes containing form routines, which belong to package VA.

**Comment by D072189** [comment]
> In my opinion we may run into this problem all the tim, when SAP generates form routine includes like this way. Another example may be Copy Control. And therefore we cannot decide on TADIR object type, because they did not have this. The are regular form routines?

The issue in this case is that the FORM routine definition statement isn't classified as generated (because a developer manually created it) - other ATC findings for the code of this routine would be perfectly justified. Note that there are many other FORM routines in the same include for which you don't get a finding - they're classified as generated. It's just the "no FORM routines" check that doesn't make sense for the manually created ones in this context, either.

In other contexts where the definition statement is classified generated (as it should be when it has been generated by SAP), you shouldn't get findings from this check. If the definition statement in VOVM or whatever isn't classified as generated, that might be a bug with the classification, but it's not the check's responsibility to fix that.

**Comment by StefanRiedel-Seifert** [comment]
Where is the classification 'generated'? That are the only attributes of the include
/1BCDWB/LSM00000008F01
![image](https://user-images.githubusercontent.com/75482283/159467927-52489644-53cd-4830-bcc1-d051b442915b.png)

That's the namespace, where SAP places the generated objects, like also for SE16.
I can open a ticket at SAP, but in my opinion they will see this not as a task for them.

Is it a problem to exclude higher-layer-level includes generically if they belong to the namespace /1BCDWB/?

**Comment by D072189** [comment]
There's a lot of bespoke logic in the ATC framework that generates this classification from various data (e.g. GENFLAG in TADIR, hard-coded lists of "known" generated includes, etc.), and I know there's specific logic that tracks which parts of the /1BCDWB/ includes generated by the smart form framework are fully generated and which contain custom code.

Includes in these generated namespace are not generically excluded from analysis because they can and do contain custom code. In fact, I think ATC used to just exclude such objects from analysis entirely but people complained about that - that's why there's the classification that works on a line-by-line basis.

Again, I think the classification is _correct_ for your example - when I tried this on one of our smart forms, I got the "Don't use FORM routines" finding only on some of the FORM definitions in the generated include, and those were precisely those that were manually written (i.e. contained code written by an actual developer).
