### ISSUE TITLE
Link to Docu of check does not work in ADT

### ISSUE THREAD

**Issue by thfiedler** [SAP/code-pal-for-abap#562]
When I use ATC with Code-PAL checks in SAP GUI there is a link within the finding to open the Github docu of the check.
In ADT the link is not available.

**Comment by D072189** [comment]
This is because the GUI documentation is obtained by calling `DISPLAY_DOCUMENTATION` on the checks, while the ADT documentation is obtained by calling `GET_DOCU_FOR_TEST`. The checks currently only reimplement the former method, and the default implementaiton of the latter tries to load classic SE61 docu that's just doesn't exist. 

There are essentially two ways to solve this:
1. Create documentation (via SE61) for every check so that the default implementation can load this.
2. Redefine `GET_DOCU_FOR_TEST` and generate the documentation (essentially just a link to the check's docu here on Github) on the fly. 

The latter is probably the cleaner way to solve this.
