### ISSUE TITLE
Incorrect finding by the check Comment Position

### ISSUE THREAD

**Issue by sachin-b-k** [SAP/code-pal-for-abap#579]
> 💡 Code pal for ABAP follows the [Clean ABAP](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md). If the issue relates to coding style, please submit it [here](https://github.com/SAP/styleguides/issues). 

**Check Name**
> Comment Position (https://github.com/SAP/code-pal-for-abap/blob/master/docs/checks/comment-position.md)

**Actual Behavior**
> In one of the report program the check is pointing to the place where in-line comments is used.

**Expected Behavior**
> As per the check it does not report findings for comments that are in-line comments

**Comment by D072189** [comment]
Please provide a reproducible example, i.e. a code snippet on which you get a finding but expect none.

**Comment by sachin-b-k** [comment]
The error is reported in the program CUAN_SUPPORT_CORRECT_IAPRODKEY at line 453 in system ABD client 100.

**Comment by D072189** [comment]
Standalone reproduction:

```abap
start-of-selection.
  types ty_string_table type standard table of string with empty key.
  data(string_table) = value ty_string_table(
    ( `1` ) "comment 1
    ( `2` ) "comment 2
    ( `3` ) ). "comment 3
```

`"comment 3` is reported although it is inline.

**Comment by D072189** [comment]
The original _intent_ of the check seems to be to report inline comments, in accordance with the [style guide](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md#put-comments-before-the-statement-they-relate-to) calling these comments "invasive" and recommending against them.

The current documentation is due to the _observed behavior_ of the check, which is not to report most inline comments - unless, like in this example, they happen to occur at the end of a statement.

The correct resolution seems to be to implement reporting all inline comments correctly and adjust the documentation to reflect that.

**Comment by sachin-b-k** [comment]
Thanks for the quick response. Since pragmas and pseudo comments are also inline comments, will those be excluded from the check.
