### ISSUE TITLE
ETA for 2.0.0 update?

### ISSUE THREAD

**Issue by abap-weasel** [SAP/code-pal-for-abap#581]
There is that big 2.0 upgrade lingering around in PR / branch https://github.com/SAP/code-pal-for-abap/tree/2.00.0 
Any timeline when that will be released to master?

**Comment by bjoern-jueliger-sap** [comment]
Honestly? Probably never. Breaking 7.40 compatibility is a no-go for the main branch of this repository, since it would make it impossible to ship fixes for the 7.40 version. Furthermore, while this would RFC enable the checks, it would not enable them to run in an ABAP Cloud Development context, which is something that's becoming increasingly more important.

We're working on a concept to develop a fully remote-enabled version of CodePal that will also be able to run in ABAP Cloud ("Steampunk") contexts. This will achieve the goals of the "2.0" pull request without any of its drawbacks. There is not much more I can share about this publicly yet, but I expect to be able to do so Soon™.
